version: '3.8'
services: 
  some.redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
       my-network:
          ipv4_address: 172.23.0.3
  some.mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=noSQLService
      - MONGO_INITDB_ROOT_PASSWORD=password123

  RedisService:
    image: redis_service
    build:
      context: ./
      dockerfile: ./RedisService/Dockerfile
    environment:  
      - RedisSection__RedisConnectionString=172.23.0.3:6379
      - RedisSection__RedisPassword=
    ports:
      - "7770:7770"
    networks:
       my-network:
          ipv4_address: 172.23.0.2
networks:
  my-network:
    external: true