version: '3.8'
services: 
  some.redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
       my-network:
          ipv4_address: 172.23.0.3
  RedisService:
    image: redis_service
    build:
      context: ./
      dockerfile: .
    environment:  
      - RedisSection__RedisConnectionString=172.23.0.3:6379
      - RedisSection__RedisPassword=
    ports:
      - "7770:7770"
    networks:
       my-network:
          ipv4_address: 172.23.0.2
networks:
  my-network:
    external: true