apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe --file .\docker-compose.yml convert
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: redisservice
  name: redisservice
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: redisservice
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe --file .\docker-compose.yml convert
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.network/my-network: "true"
        io.kompose.service: redisservice
    spec:
      containers:
        - env:
            - name: redissection__redisconnectionstring
              value: 172.17.0.6:6379
            - name: redissection__redispassword
          image: nordennavic/redisservice
          name: redisservice
          ports:
            - containerPort: 7770
          resources: {}
      restartPolicy: Always
status: {}
