apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe --file .\docker-compose.yml convert
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: redisservice
  name: redisservice
spec:
  type: NodePort
  ports:
    - port: 7770
      targetPort: 7770
      nodePort: 30001
  selector:
    io.kompose.service: redisservice
status:
  loadBalancer: {}
