apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe --file .\docker-compose.yml convert
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: some-redis
  name: some-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: some-redis
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe --file .\docker-compose.yml convert
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.network/my-network: "true"
        io.kompose.service: some-redis
    spec:
      containers:
        - image: redis
          name: some-redis
          ports:
            - containerPort: 6379
          resources: {}
      restartPolicy: Always
status: {}
